# This informs travis to use a docker container
sudo: false

# Since we're using a container, we can cache specified directories
# Specifally, let's cache haskell-stack related stuff since it's slow to rebuild
cache:
  directories:
  - $HOME/.stack

language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

# Since this container can't sudo, we need to specify additional packages to install
addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      # haskell compiler
      - ghc-7.10.2
      # needed by some haskell package
      - libgmp3-dev

before_install:
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - mkdir -p ~/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - stack setup

script:
  - stack --skip-ghc-check install caut-rust-ref
  - stack --skip-ghc-check install crucible
  - sh run_crucible.sh
