language: rust
matrix:
  include:
    - rust: "nightly"
script:
  - cargo build --verbose --manifest-path static/cauterize/Cargo.toml
  - cargo test --verbose --manifest-path static/cauterize/Cargo.toml
