sudo: false

language: c

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-7.10.2
    - libgmp3-dev

before_install:
  - export PATH=/opt/ghc/7.10.2/bin:$PATH
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - mkdir -p ~/.cargo/bin
  - export PATH=$HOME/.cargo/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - stack setup
  - rustup override set nightly

script:
  - stack --skip-ghc-check install caut-rust-ref
  - stack --skip-ghc-check install crucible
  - sh run_crucible.sh
