flags: {}

packages:
- .

extra-deps:
- git: https://github.com/cauterize-tools/cauterize.git
  commit: e07434771d39961d89159add7fdacbedf1d9ff14
- git: https://github.com/cauterize-tools/crucible.git
  commit: 5c0056f6bb07cee381572a4a2db548be47e955aa
- GraphSCC-1.0.4
- Interpolation-0.3.0
- s-cargot-0.1.4.0
- wl-pprint-1.2.1

resolver: lts-12.9
