[package]
name = "aey"
version = "0.1.0"
authors = ["author"]

[lib]
name = "aey"
path = "src/aey.rs"

[[bin]]
name = "tester"
path = "bin/tester.rs"

[dependencies]
byteorder = "0.5"

[dev-dependencies]
quickcheck = "0.2"
quickcheck_macros = "0.2"
